In [1]:
import numpy as np
a=np.array([1,2,3])
b=np.array([5,6,7])
print(a+b)
print(b-a)
print(a*b)
print(b/a)
print(b%a)
print(b//a)
print(a**b)

[ 6  8 10]
[4 4 4]
[ 5 12 21]
[5.         3.         2.33333333]
[0 0 1]
[5 3 2]
[   1   64 2187]
